<?php

/**
 * @file
 * Module file for the OCHA AI Chat module.
 */

/**
 * Implements hook_file_download().
 *
 * Allow access to log files to people with the permission to see the logs.
 */
function ocha_ai_chat_file_download(string $uri): mixed {
  if (
    strpos($uri, 'private://ocha_ai_chat_logs/') === 0 &&
    pathinfo($uri, \PATHINFO_EXTENSION) === 'csv' &&
    \Drupal::currentUser()->hasPermission('view ocha ai chat logs')
  ) {
    $filename = \Drupal::service('file_system')->basename($uri);
    return [
      'Content-Disposition' => 'attachment; filename="' . $filename . '"',
      'Content-Length' => filesize($uri),
      'Content-Type' => 'text/csv',
      'Cache-Control' => 'private',
    ];
  }
  return NULL;
}
