_core:
  default_config_hash: sEceqho82ErW-swOq9gnnEcaTFTiX_lrtpKL2ypdmmg
plugins:
  completion:
    aws_bedrock:
      model: amazon.titan-text-express-v1
      endpoint: ''
      version: ''
      region: REPLACE_WITH_REGION
      api_key: REPLACE_WITH_KEY
      api_secret: REPLACE_WITH_SECRET
      max_tokens: 512
      prompt_template: "SYSTEM: You are a helpful assistant. Answer the user's question concisely and exactly, using only the following information. Write complete sentences. Say you don't know if you cannot answer.\n\n{{ context }}\n\nQUESTION: {{ question }}\n\nANSWER:"
      role_arn:
    azure_openai:
      model: gpt-3.5-turbo
      endpoint: REPLACE_WITH_ENDPOINT
      version: '2023-05-15'
      region: REPLACE_WITH_REGION
      api_key: REPLACE_WITH_KEY
      max_tokens: 512
      prompt_template: "You are a helpful assistant. Answer the user's question concisely and exactly, using only the following information. Write complete sentences. Say you don't know if you cannot answer.\n\n{{ context }}"
  embedding:
    aws_bedrock:
      model: amazon.titan-embed-text-v1
      endpoint: ''
      version: ''
      region: REPLACE_WITH_REGION
      api_key: REPLACE_WITH_KEY
      api_secret: REPLACE_WITH_SECRET
      batch_size: 1
      dimensions: 1536
      max_tokens: 256
      role_arn:
    azure_openai:
      model: text-embedding-ada-002
      endpoint: REPLACE_WITH_ENDPOINT
      version: '2023-05-15'
      region: REPLACE_WITH_REGION
      api_key: REPLACE_WITH_KEY
      batch_size: 16
      dimensions: 1536
      max_tokens: 4096
  source:
    reliefweb:
      api_url: 'https://api.reliefweb.int/v1'
      converter_url: 'https://reliefweb.int/search/converter/json'
      appname: ocha-ai-chat
      cache_enabled: true
      cache_lifetime: 600
  text_extractor:
    mupdf:
      mutool: /usr/bin/mutool
  text_splitter:
    sentence:
      length: '4'
      overlap: '2'
  vector_store:
    elasticsearch:
      url: REPLACE_WITH_URL
      indexing_batch_size: 10
      topk: 5
defaults:
  plugins:
    completion:
      plugin_id: aws_bedrock
    embedding:
      plugin_id: aws_bedrock
    source:
      plugin_id: reliefweb
    text_extractor:
      application/pdf:
        plugin_id: mupdf
    text_splitter:
      plugin_id: sentence
    vector_store:
      plugin_id: elasticsearch
