_core:
  default_config_hash: u1i8zeMVukBrBTceOihklpjtAaIecFZh8jMIxYb67OU
reliefweb_api_url: 'https://api.reliefweb.int/v1'
reliefweb_api_appname: unocha.org
reliefweb_api_cache_enabled: true
reliefweb_api_cache_lifetime: 300
reliefweb_api_verify_ssl: true
reliefweb_website: 'https://reliefweb.int'
reliefweb_api_converter: 'https://reliefweb.int/search/converter/json'
reliefweb_api_use_redirects: true
