ocha_reliefweb_api.settings:
  type: config_object
  label: 'UNOCHA ReliefWeb integration settings'
  mapping:
    reliefweb_api_url:
      type: string
      label: 'ReliefWeb API URL'
    reliefweb_api_appname:
      type: string
      label: 'App name parameter to indentify the API requests.'
    reliefweb_api_cache_enabled:
      type: boolean
      label: 'Cache the API query results.'
    reliefweb_api_cache_lifetime:
      type: integer
      label: 'How long to cache the API query results.'
    reliefweb_api_verify_ssl:
      type: boolean
      label: 'Verify the SSL certificate of the API query performing requests.'
    reliefweb_website:
      type: string
      label: 'ReliefWeb site URL.'
    reliefweb_api_converter:
      type: string
      label: 'URL of the ReliefWeb API converter.'
    reliefweb_api_use_redirects:
      type: boolean
      label: 'Also use the "redirects" field for URL lookups.'
